# Generated by Django 3.0.4 on 2020-03-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBio', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
    ]
