# Generated by Django 3.0.4 on 2020-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBio', '0004_parcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointBiodiversite',
            fields=[
                ('idPoint', models.AutoField(primary_key=True, serialize=False)),
                ('nomFr', models.CharField(max_length=120)),
                ('nomSc', models.CharField(max_length=120)),
                ('idFamille', models.IntegerField()),
                ('idParcours', models.IntegerField()),
                ('numeroParcours', models.IntegerField()),
                ('ecorceRemarquable', models.BooleanField(default=False)),
            ],
        ),
    ]
