# Generated by Django 3.0.4 on 2020-03-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointBio', '0005_pointbiodiversite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointBio',
        ),
        migrations.AlterField(
            model_name='pointbiodiversite',
            name='idFamille',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pointbiodiversite',
            name='idParcours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pointbiodiversite',
            name='numeroParcours',
            field=models.PositiveIntegerField(),
        ),
    ]
