# Generated by Django 3.0.4 on 2020-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PointBiodiversite',
            fields=[
                ('idPoint', models.AutoField(primary_key=True, serialize=False)),
                ('nomFr', models.CharField(max_length=120)),
                ('nomSc', models.CharField(max_length=120)),
                ('idFamille', models.PositiveIntegerField()),
                ('idParcours', models.PositiveIntegerField()),
                ('numeroParcours', models.PositiveIntegerField()),
                ('ecorceRemarquable', models.BooleanField(default=False)),
            ],
        ),
    ]
