# Generated by Django 3.0.4 on 2020-04-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointbiodiversite',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodiversite.Famille'),
        ),
    ]
