# Generated by Django 3.0.4 on 2020-04-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversite', '0002_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='pointbiodiversite',
            table='pointBio',
        ),
    ]
