# Generated by Django 3.0.4 on 2020-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversite', '0002_pointbiodiversite_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointbiodiversite',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
    ]
