# Generated by Django 3.0.4 on 2020-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversite', '0003_auto_20200424_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointbiodiversite',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
    ]
