# Generated by Django 3.0.4 on 2020-04-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversite', '0003_auto_20200411_1011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='famille',
            table='familles',
        ),
        migrations.AlterModelTable(
            name='parcours',
            table='parcours',
        ),
    ]
